### ISSUE TITLE
support for starting criculation

### ISSUE THREAD

**Issue by thomasgermain** [thomasgermain/vaillant-component#19]
@h4de5, it would be better to talk about that here :smiley: 

So you are talking about the circulation of the domestic hot water right ? I just check and this is not possible to control the circulation through the API. maybe you can have a look at hotwater boost, according to the doc, it sets the circulation ON

**Comment by h4de5** [comment]
Good idea. So domestic hot water... Maybe?

This is what I see in the app: 
![Screenshot_20200831-221543](https://user-images.githubusercontent.com/6115324/91764446-9c3d9900-ebd7-11ea-829f-d392384b1a98.png)
![Screenshot_20200831-221619](https://user-images.githubusercontent.com/6115324/91764499-b4151d00-ebd7-11ea-8415-084d4b8d5aa5.png)

Right now its programmed to run 3 times a day. But of course it would make much more sense if I could actually turn it on when i need it.

Hot water boost? Is this one of the special programs like "1-mal speicherladung"?

**Comment by h4de5** [comment]
Just had a look at the docs: https://thomasgermain.github.io/pymultiMATIC/build/html/modes.html#pymultimatic.model.quick_mode.QuickModes.HOTWATER_BOOST

Seems what I thought. Just testet it through the app and the circulation came on as you said. 👍 

So to trigger that through hass, I use the service "vaillant.set_quick_mode" with?

**Comment by h4de5** [comment]
It says it right there.. QM_HOTWATER_BOOST.

Why can't you read "me-from-the-past".

I think this is done.

**Comment by thomasgermain** [comment]
so yeah, it should do the trick. I just checked the doc: http://elearning.vaillant.com/vrc700/ci/en/documents/uk/infopool/Operating_instructions.pdf

```
Operating mode → Cylinder boost
– If you have switched off hot water generation or require
hot water outside of a time period, activate the Cylinder
boost advanced function.

The advanced function heats the water in the domestic hot
water cylinder once until the desired DHW circuit temperature set is reached or until you cancel the advanced function
early. The heating installation will then return to the pre-set
mode.
```

It doesn't state anything about circulation, but i'm pretty sure I read that circulation is on when this mode is activate

**Comment by h4de5** [comment]
here a script:

scripts.yaml
```yaml
hotwater_boost:
  alias: Start hotwater boost program and circulation for 10 minutes
  icon: mdi:thermometer-plus
  mode: single
  sequence:
  - data:
      quick_mode: QM_HOTWATER_BOOST
    service: vaillant.set_quick_mode
  - timeout: 00:10:00
    wait_template: ''
  - data: {}
    service: vaillant.remove_quick_mode
```

automations.yaml
```yaml
- id: '1598910266712'
  alias: Start Boostprogram on state change
  trigger:
  - entity_id: light.erster_stock_bad_licht_5
    for: 00:00:10
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    service: script.hotwater_boost
  mode: single
```
