### ISSUE TITLE
Missing Icons in tile card

### ISSUE THREAD

**Issue by PV-Joe** [thomasgermain/vaillant-component#230]
Hi Thomas,

thank you for this great implementation and the good work of keeping it up to date.

By using the tile card I have seen that there are some missing icons for the Hot Water modes. Could you please add them?

In the „Working Mode“ the icons for day, party and system_off are missing as well.

Hoping for a fix within the next update.
Joe
![IMG_4504](https://github.com/thomasgermain/vaillant-component/assets/110498562/b405bdd6-876a-4fbf-9064-36bff2ad9e1c)

![IMG_4505](https://github.com/thomasgermain/vaillant-component/assets/110498562/8fac2e44-89b6-4aa9-ae0f-8ba7f66ab374)

**Comment by thomasgermain** [comment]
Hi, 

thanks for the feedback :)

Are you using lovelace in manual mode ? If yes, can you post for lovelace for the climate card ?

As far as I know, there is no way to translate nor to have icon for custom presets (e.g. `system_off` is a custom preset). I will dig a bit

**Comment by PV-Joe** [comment]
> Hi,
> 
> thanks for the feedback :)
> 
> Are you using lovelace in manual mode ? If yes, can you post for lovelace for the climate card ?
> 
> As far as I know, there is no way to translate nor to have icon for custom presets (e.g. `system_off` is a custom preset). I will dig a bit

… I used a tile card and chose the entity. That‘s it. No manual yaml used.

**Comment by thomasgermain** [comment]
It sounds to work well:
![image](https://github.com/thomasgermain/vaillant-component/assets/12560542/1ffcab3d-cd7d-4f14-8556-f0d5e94d23a1).

According to the doc, you have to specify which hvac actions you want to be displayed: https://www.home-assistant.io/dashboards/tile/#climate-hvac-modes

**Comment by PV-Joe** [comment]
Here is the yaml code.
Any suggestions how to modify?

features:
  - type: climate-hvac-modes
    hvac_modes:
      - auto
      - 'off'
  - type: target-temperature
  - style: dropdown
    preset_modes:
      - comfort
      - day
      - sleep
      - home
      - party
      - away
      - system_off
    type: climate-preset-modes
type: tile
entity: climate.control_zo1_21223200202609620938058313n1
name: Modus
vertical: false

**Comment by PV-Joe** [comment]
Here is the yaml. Any idea what to modify?

```

features:
  - type: climate-hvac-modes
    hvac_modes:
      - auto
      - 'off'
  - type: target-temperature
  - style: dropdown
    preset_modes:
      - comfort
      - day
      - sleep
      - home
      - party
      - away
      - system_off
    type: climate-preset-modes
type: tile
entity: climate.control_zo1_21223200202609620938058313n1
name: Modus
vertical: false

```

**Comment by PV-Joe** [comment]
… and here is the other codeblock:

```

features:
  - type: target-temperature
  - type: water-heater-operation-modes
    operation_modes:
      - 'ON'
      - 'OFF'
      - AUTO
type: tile
entity: water_heater.control_dhw_21223200202609620938058313n1
name: Heißwssser
show_entity_picture: false

```
