### ISSUE TITLE
HistoryGraph for working status of water heater and heating

### ISSUE THREAD

**Issue by martinkutter** [thomasgermain/vaillant-component#38]
Hello, first of all, thank you for this great work on this integration.

Is it possible to read out the status if heating and hot water are currently in operation, i.e. whether the system is currently running?

I would like to have a historygraph like the one for the status of the circulation.

**Comment by thomasgermain** [comment]
Hello,

so, if I understand well, you want to know when heating and hot water are actually heating ?

For climate entities, you have an sate attributes `hvac_action` (`idle`, `heating` or `cooling`). 
For hot water, there is nothing to indicate (from vaillant API) if the hot water is currently heating
For circulation, this is a binary sensor, so I guess you can check when it's `on`

**Comment by martinkutter** [comment]
Thank you for the quick response!

My heating system is a water pumpe. Actually, I wanted to know when exactly the heat pump is working. If you compare the values with the heating curve, it should always be exactly the period when the water temperature rises quickly until the time when it slowly falls again. So `hvac_action` is not what I expected. Are there any other possibilities?

![image](https://user-images.githubusercontent.com/16589094/110953234-6841ee00-8347-11eb-9707-895c5e3a748c.png)

**Comment by thomasgermain** [comment]
From where (which entity ?) did you get the second graph (with idle/heating) ?

**Comment by martinkutter** [comment]
`hvac_action` attribute from `climate` entity.

```
  - platform: template
    sensors:
      heizung_status:
        friendly_name: "Heizung Status"
        value_template: "{{ state_attr('climate._control_zo1', 'hvac_action') }}"
```
