### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by mjurkic** [thomasgermain/vaillant-component#98]
Hello!
First of all, thanks for creating this, it works like a charm!

I was wondering if it would be possible to enable statistics for the temperature sensors, as per this link: https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Apologies if I asked a silly question.

Thanks
Matej

**Comment by thomasgermain** [comment]
Hello,

Actually, I don't really know if this is up to integrations to do long term stats for every entities. You can also do some template entities, you should be able to have the same state as a given entity and add state_class and/or device_class:

```yaml
sensor:
  - name: xxx
    unique_id: myid
    state: "{{states('sensor.xxx')}"
    unit_of_measurement: '..'
    state_class: 'measurement'
```

Anyway, I can also add `state_class` to the entities created by the integration

**Comment by thomasgermain** [comment]
This release https://github.com/thomasgermain/vaillant-component/releases/tag/1.10.0 should fits your needs :), please let me know if it works

**Comment by mjurkic** [comment]
Thank you very much, I can confirm that the water pressure, outdoor temp and flow temp sensors now have statistics - but not the individual valves - I'm just a newbie so apologies as I still need to figure what are entities and if it would even be possible to store this statistical data for all elements.

Basically, I'd like a way to store long term data on (mostly) temperature movements in each room, outdoors, etc.

Thanks for the brilliant work btw :)

**Comment by thomasgermain** [comment]
Rooms/Zones temperature are not entities, they are attribute of climate entities (thus I can't make climate entity compatible with long term stats).  

But you can extract the `current_temperature` attribute from the climate entity and make it a stats compatible entity, something like that should do the trick:

```yaml
sensor:
  - name: xxx
    unique_id: myid
    state: "{{state_attr('climate.control_zo2', 'current_temperature')}}"
    unit_of_measurement: '°C'
    state_class: 'measurement'
```
